### ISSUE TITLE
You posted one Fokke & Sukke 15 times. And the one before that three times

### ISSUE THREAD

**Issue by jjwa** [ondergetekende/stripposter#10] opened 2017-10-29 19:23 UTC
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=348777bac3f7f21886561a9b369c04e5
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=9835249986a4916a40f4116f60dd21d3
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=ad48266539115a49c94d459ca7893a73
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=c238313af5d982323c269fb3092c470d
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=427eee6cda350cd9009ea5bb30b796d8
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=a78600774b0a2c178b6e34cb6bc57331
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=8164091cdf24744dc79b4dce7578782b
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=150907ec7f497daf7a9800333efb115b
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=81ae0eb9c60682d61ada85731cddd2e0
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=c0fe5cd8666afbee32009717b99da588
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=92db18a9691b2c0b8a7119a870d92890
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=f0082d525583da755adea407ac3d69e2
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=03e011e48104f9851b8f23ad8f181258
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=4976be75bf39cfcf7e953ebf8e3bae06
http://www.foksuk.nl/nl?cm=79&ctime=1508968800&session=26150e934cc3a61a7a49ac11b514a1cb

http://www.foksuk.nl/nl?cm=79&ctime=1508882400&session=fa34a77b59bd2678b96d392c3a02fd4e
http://www.foksuk.nl/nl?cm=79&ctime=1508882400&session=6da434c88db92639c9a92f484740304b
http://www.foksuk.nl/nl?cm=79&ctime=1508882400&session=70c1f99b7c990f51db527c7521d1a78b

**Comment by kvdveer** [comment] 2017-10-29 20:36
Thanks for noticing this, the issue has now been resolved. (although the
duplicate posts remain)

Duplicate of #9

**Closed as completed** 2018-12-14 07:57 UTC
